remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ["Boffin Build Project - Piano Staircase"]
description: ["Support provided by the Students First Fund of the Wright State University Foundation"]
